### ISSUE TITLE
Logout is configured as GET endpoint instead of POST 

### ISSUE THREAD

**Issue by alexisgra** [TNG/keycloak-mock#172]
The logout endpoint (end_session_endpoint field of the .well-known) is configured as a GET endpoint in the router. It appears to be a POST instead.
I want to use it in my integration tests, but it returns a 405 Method not Allowed.

I can make a pull request.
Thanks

**Comment by ostrya** [comment]
You raise a valid point. According to https://openid.net/specs/openid-connect-rpinitiated-1_0.html, both POST and GET should be supported. I'll fix it, should be straightforward.

**Comment by alexisgra** [comment]
Thank you very much @ostrya 🙏
