### ISSUE TITLE
Help with setup instructions

### ISSUE THREAD

**Issue by lambdaclan** [TNG/keycloak-mock#52]
Hello there.

First of all thank you very much for your work.

I was wondering if it is possible to use this library without spring framework. I am developing custom Keycloak REST endpoints and want some way to test them out. Currently I am using docker to make sure the endpoints work as expected but if there is a way to make use of the mock instead it would be great.

My setup is not as complicated as the examples you provide in this repo. All I have are the two files to define custom REST endpoints (RealmResourceProvider and RealmResourceProviderFactory) then I deploy them via docker for manual testing purposes.

For example looking at the Keycloak provider examples here: https://github.com/keycloak/keycloak/tree/master/examples/providers/rest would it be possible somehow to test the simple [GET](https://github.com/keycloak/keycloak/blob/master/examples/providers/rest/src/main/java/org/keycloak/examples/rest/HelloResourceProvider.java#L42) request using this mock library?

Thank you for your help.

Edit:

Currenrly I can test the endpoints if I first launch a local server and then run the tests:

![image](https://user-images.githubusercontent.com/47409392/102680914-4b8e9200-4200-11eb-8c0e-eac457eecfc8.png)

```java
  @Test
  public void getHello() {
    RestAssured.given().when().get("http://localhost:8080/auth/realms/master/hello").then().statusCode(200);
  }

```

**Comment by ostrya** [comment]
As far as I understand it, you want to extend your Keycloak server instance by custom controllers. Is that right?

In this case, this library is not the right point to start, I am afraid. Keycloak-Mock is meant to be used for developing resource servers that delegate authentication to a Keycloak server.

For your purposes I suggest looking into registering the resource you have written into an embedded RESTEasy server within your test. See e.g. https://docs.jboss.org/resteasy/docs/4.5.8.Final/userguide/html_single/index.html#RESTEasy_Embedded_Container .

**Comment by lambdaclan** [comment]
Hello thank you very much for your reply and willingness to help out even though it seems this library cannot be used for what I am trying to do.

I had a quick look at the link you have kindly provided me with and it does look promising. The problem is that some resources (custom endpoints) do require a running Keycloak server which is why I thought this library could be potentially used.

For example trying to have a resource that requires authentication it [polls the server](https://github.com/keycloak/keycloak/blob/master/examples/providers/domain-extension/src/main/java/org/keycloak/examples/domainextension/rest/ExampleRestResource.java#L34) to see if the requester has a valid role.

I guess there is no workaround for that? 

Using docker might be the easiest option after all. I was hoping to be able to setup a keycloak mock server with a few  configurations such as available roles etc.

**Comment by ostrya** [comment]
As I suspected, there is little I can do to help. If you need server internals like the KeycloakSession, you probably either need to deploy your Resource to an actual Keycloak instance or you need to mock the corresponding logic using standard mocking libraries. This library is only meant for Keycloak client applications.
