### ISSUE TITLE
Enable basic authentification configuration

### ISSUE THREAD

**Issue by jutant-l** [TNG/keycloak-mock#70]
First, i would like to configure this option :
`"enable-basic-auth" : false,`

In a second time i want to authorize request with header :
`Authorization: basic BASE64(client-id + ':' + client-secret)`

So can you add enable-basic-auth configuration and add a user registration ?

**Comment by ostrya** [comment]
@jutant-l  we have added support for confidential clients with release v0.9.0. Can you please check if this fits your use case?

**Comment by marcelocamanho** [comment]
> @jutant-l we have added support for confidential clients with release v0.9.0. Can you please check if this fits your use case?

does it support acquiring a token for a confidential client doing a

POST realms/{realm}/protocol/openid-connect/token?client_id={client}&grant_type=confidential&client_secret={secret}
Headers: "Content-Type: application/x-www-form-urlencoded", "Accept: application/json"

i am trying 0.10.0 and it doesnt seem to work, but im not sure if im doing anything wrong..
it does work with Keycloak / Redhat SSO

**Comment by ostrya** [comment]
Ah, I see. The initial implementation only supports Basic Auth. I'll put form based authentication to the todo list :)

Tech hint: https://datatracker.ietf.org/doc/html/rfc6749#section-2.3.1

**Comment by marcelocamanho** [comment]
> Ah, I see. The initial implementation only supports Basic Auth. I'll put form based authentication to the todo list :)
> 
> Tech hint: https://datatracker.ietf.org/doc/html/rfc6749#section-2.3.1

Added a PR :)
https://github.com/TNG/keycloak-mock/pull/99

**Comment by ostrya** [comment]
Fixed with version v0.11.0.
